In [1]:
import datetime
from dateutil import parser

import yaml
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

from ftx import FtxClient
import trade_analysis as ta

In [2]:
with open("configuration.yml", "r") as f:
    config = yaml.safe_load(f)

In [3]:
ftx = FtxClient(api_key=config["ftx"]["api_key"],
                api_secret=config["ftx"]["api_secret"],
                subaccount_name=config["ftx"]["account"])

In [5]:
start_time = datetime.datetime.strptime("2022-01-24 09:38", "%Y-%m-%d %H:%M").replace(tzinfo=datetime.timezone.utc).timestamp()
end_time = datetime.datetime.utcnow().timestamp()

In [6]:
data = ftx.get_historical_data("BTC-PERP", resolution=300, limit=5000, start_time=start_time, end_time=end_time)

In [10]:
df = pd.DataFrame(columns=["time", "open", "high", "low", "close", "volume"])

for idx, d in enumerate(data):
    df.loc[idx] = [parser.parse(d["startTime"]), d["open"], d["high"], d["low"], d["close"], d["volume"]]

In [11]:
df

,time,open,high,low,close,volume
0,2022-01-24 09:40:00+00:00,34600.0,34627.0,34480.0,34530.0,2.149404e+07
1,2022-01-24 09:45:00+00:00,34530.0,34694.0,34438.0,34563.0,2.401616e+07
2,2022-01-24 09:50:00+00:00,34563.0,34693.0,34545.0,34603.0,1.593447e+07
3,2022-01-24 09:55:00+00:00,34602.0,34629.0,34418.0,34519.0,1.777519e+07
4,2022-01-24 10:00:00+00:00,34519.0,34598.0,34468.0,34522.0,1.413946e+07
...,...,...,...,...,...,...
413,2022-01-25 20:05:00+00:00,36970.0,36977.0,36814.0,36855.0,3.310339e+07
414,2022-01-25 20:10:00+00:00,36857.0,36910.0,36827.0,36850.0,2.233337e+07
415,2022-01-25 20:15:00+00:00,36850.0,36933.0,36845.0,36917.0,1.135088e+07
416,2022-01-25 20:20:00+00:00,36917.0,37011.0,36829.0,36836.0,1.504966e+07
417,2022-01-25 20:25:00+00:00,36836.0,36889.0,36781.0,36797.0,7.036897e+06